# Generated by Django 4.2.2 on 2023-07-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('health', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=50)),
                ('speed', models.IntegerField(default=50)),
                ('defense', models.IntegerField(default=1)),
                ('dodge', models.IntegerField(default=1)),
                ('block', models.IntegerField(default=1)),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_class', to='main_app.character_class')),
            ],
        ),
    ]
