# Generated by Django 4.2.2 on 2023-07-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
