# Generated by Django 4.2.2 on 2023-07-13 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_character_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bonushealth',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)]),
        ),
    ]
