# Generated by Django 4.2.2 on 2023-07-13 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_character_bonushealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bonushealth',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Bonus Health'),
        ),
    ]
