# Generated by Django 4.2.2 on 2023-07-13 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_character_bonushealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bonusblock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Bonus Block'),
        ),
        migrations.AddField(
            model_name='character',
            name='bonuscounter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Bonus Counter'),
        ),
        migrations.AddField(
            model_name='character',
            name='bonusdefense',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Bonus Defense'),
        ),
        migrations.AddField(
            model_name='character',
            name='bonusdodge',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Bonus Dodge'),
        ),
        migrations.AddField(
            model_name='character',
            name='bonusspeed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Bonus Speed'),
        ),
        migrations.AddField(
            model_name='character',
            name='bonusstrength',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Bonus Strength'),
        ),
    ]
