# Generated by Django 4.2.2 on 2023-07-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_character_bonusblock_character_bonuscounter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bonusblock',
            field=models.IntegerField(default=0, verbose_name='Bonus Block'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bonuscounter',
            field=models.IntegerField(default=0, verbose_name='Bonus Counter'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bonusdefense',
            field=models.IntegerField(default=0, verbose_name='Bonus Defense'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bonusdodge',
            field=models.IntegerField(default=0, verbose_name='Bonus Dodge'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bonushealth',
            field=models.IntegerField(default=0, verbose_name='Bonus Health'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bonusspeed',
            field=models.IntegerField(default=0, verbose_name='Bonus Speed'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bonusstrength',
            field=models.IntegerField(default=0, verbose_name='Bonus Strength'),
        ),
    ]
