# Generated by Django 4.2.2 on 2023-07-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_character_bonusblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name="Armor's Name")),
                ('image', models.CharField(max_length=250, verbose_name='Image')),
                ('durability', models.IntegerField(default=0, verbose_name="Armor's Durability")),
                ('health', models.IntegerField(default=0, verbose_name='Bonus Health')),
                ('defense', models.IntegerField(default=0, verbose_name='Bonus Defense')),
                ('magic_defense', models.IntegerField(default=0, verbose_name='Bonus Magic Defense')),
                ('health_regen', models.IntegerField(default=0, verbose_name='Bonus Health Regeneration')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name="Weapon's Name")),
                ('image', models.CharField(max_length=250, verbose_name='Image')),
                ('strength', models.IntegerField(default=0, verbose_name='Bonus Strength')),
                ('block', models.IntegerField(default=0, verbose_name='Bonus Block Chance')),
                ('counter', models.IntegerField(default=0, verbose_name='Bonus Counter Chance')),
                ('crit', models.IntegerField(default=0, verbose_name='Critical Hit Chance')),
                ('armor_piercing', models.IntegerField(default=0, verbose_name='Armor Piercing')),
                ('life_steal', models.IntegerField(default=0, verbose_name='Life Steal')),
                ('poison_chance', models.IntegerField(default=0, verbose_name='Poison Chance')),
                ('poison_damage', models.IntegerField(default=0, verbose_name='Poison Damage')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.TextField(default='', max_length=1000, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_class', to='main_app.character_class', verbose_name='Character Class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.CharField(max_length=250, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='character_class',
            name='block',
            field=models.IntegerField(default=1, verbose_name='Block Chance'),
        ),
        migrations.AlterField(
            model_name='character_class',
            name='counter',
            field=models.IntegerField(default=1, verbose_name='Counter Chance'),
        ),
        migrations.AlterField(
            model_name='character_class',
            name='defense',
            field=models.IntegerField(default=1, verbose_name='Defense'),
        ),
        migrations.AlterField(
            model_name='character_class',
            name='dodge',
            field=models.IntegerField(default=1, verbose_name='Dodge Chance'),
        ),
        migrations.AlterField(
            model_name='character_class',
            name='health',
            field=models.IntegerField(default=100, verbose_name='Health'),
        ),
        migrations.AlterField(
            model_name='character_class',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='character_class',
            name='speed',
            field=models.IntegerField(default=50, verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='character_class',
            name='strength',
            field=models.IntegerField(default=50, verbose_name='Strength'),
        ),
    ]
