# Generated by Django 4.2.2 on 2023-07-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_armor_weapon_alter_character_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='armor', to='main_app.armor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='main_app.weapon'),
            preserve_default=False,
        ),
    ]
