# Generated by Django 4.2.2 on 2023-07-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_character_armor_character_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='background',
            field=models.TextField(default='', max_length=1000, verbose_name='Background'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='background',
            field=models.TextField(default='', max_length=1000, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bonusblock',
            field=models.IntegerField(default=0, verbose_name='Bonus Block Chance'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bonuscounter',
            field=models.IntegerField(default=0, verbose_name='Bonus Counter Chance'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bonusdodge',
            field=models.IntegerField(default=0, verbose_name='Bonus Dodge Chance'),
        ),
    ]
