# Generated by Django 4.2.2 on 2023-07-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_armor_background_weapon_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armor', to='main_app.armor', verbose_name='Armor'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='main_app.weapon', verbose_name='Weapon'),
        ),
    ]
