# Generated by Django 4.2.2 on 2023-07-18 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_armor_background_alter_character_background_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name="Spell's Name")),
                ('image', models.CharField(max_length=250, verbose_name='Image')),
                ('description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Description')),
                ('on_use', models.CharField(blank=True, default='', max_length=100, verbose_name='On Use')),
                ('water_damage', models.IntegerField(default=0, verbose_name='Water Damage')),
                ('earth_damage', models.IntegerField(default=0, verbose_name='Earth Damage')),
                ('fire_damage', models.IntegerField(default=0, verbose_name='Fire Damage')),
                ('air_damage', models.IntegerField(default=0, verbose_name='Air Damage')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='spell1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spell1', to='main_app.spell', verbose_name='Spell 1'),
        ),
        migrations.AddField(
            model_name='character',
            name='spell2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spell2', to='main_app.spell', verbose_name='Spell 2'),
        ),
        migrations.AddField(
            model_name='character',
            name='spell3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spell3', to='main_app.spell', verbose_name='Spell 3'),
        ),
        migrations.AddField(
            model_name='character',
            name='spell4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spell4', to='main_app.spell', verbose_name='Spell 4'),
        ),
    ]
