# Generated by Django 4.2.2 on 2023-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_spell_character_spell1_character_spell2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bonuscombo',
            field=models.IntegerField(default=0, verbose_name='Bonus Combo Chance'),
        ),
        migrations.AddField(
            model_name='character_class',
            name='combo',
            field=models.IntegerField(default=0, verbose_name='Combo Chance'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='combo',
            field=models.IntegerField(default=0, verbose_name='Combo Chance'),
        ),
    ]
