# Generated by Django 4.2.2 on 2023-07-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_character_bonuscombo_character_class_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bonusmagicdefense',
            field=models.IntegerField(default=0, verbose_name='Bonus Magic Defense'),
        ),
    ]
