# Generated by Django 4.2.2 on 2023-07-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_character_bonusmagicdefense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name="Weapon's Name"),
        ),
    ]
