# Generated by Django 4.2.2 on 2023-07-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_weapon_image_alter_weapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(blank=True, default='11', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='weapon', to='main_app.weapon', verbose_name='Weapon'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.CharField(blank=True, default=' ', max_length=250, verbose_name='Image'),
        ),
    ]
