# Generated by Django 4.2.2 on 2023-07-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_armor_defense_alter_armor_durability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_class',
            name='magic_defense',
            field=models.IntegerField(default=1, verbose_name='Magic Defense'),
        ),
    ]
