# Generated by Django 4.2.2 on 2023-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_armor_dodge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='background',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='background',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Background'),
        ),
    ]
